General:
  operation: "synthesization"
  model_path: "../models/Llama-3.1-8B-Instruct/Base"

Data:
  prompt_template_path: "templates/generator.txt"
  sample_size: 5
  dataset_path: "data/test.csv"
  seed: 42

Training:
  max_new_tokens: 512
  temperature: 0.8
  top_k: 50
  top_p: 0.9
  do_sample: true
  repetition_penalty: 1.1
  num_return_sequences: 1

