General:
  operation: "synthesization_leo"
  generator_model_path: "../models/Llama-3.1-8B-Instruct/Base"
  discriminator_model_path: "../models/Llama-3.2-1B-Instruct/Base"

Data:
  generator_prompt_template_path: "templates/generator.txt"
  discriminator_prompt_template_path: "templates/discriminator.txt"
  sample_size: 5
  output_size: 1
  dataset_path: "data/public/test.csv"
  output_path: "data/synthetic/generated_data.csv"
  seed: 42

Training:
  max_new_tokens: 512
  temperature: 0.8
  top_k: 50
  top_p: 0.9
  do_sample: true
  repetition_penalty: 1.1
  num_return_sequences: 1