General:
  operation: "training"
  generator_name_or_path: "../models/Llama-3.2-3B-Instruct/Base"
  discriminator_name_or_path: "../models/Llama-3.2-1B-Instruct/Base"

Data:
  prompt_template_path: "templates/generator.txt"
  generator_prompt_template_path: "templates/generator.txt"
  discriminator_prompt_template_path: "templates/discriminiator.txt"
  sample_size: 5
  output_size: 1
  dataset_path: "data/public/test2.csv"
  output_path: "data/synthetic/generated_data.csv"
  seed: 42

Training:
  generator_lr: 5e-5
  discriminator_lr: 5e-5
  alpha: 0.5
  num_epochs: 3
  batch_size: 16
  output_dir: "../models/LLMGAN"


  max_new_tokens: 512
  temperature: 0.8
  top_k: 50
  top_p: 0.9
  do_sample: true
  repetition_penalty: 1.1
  num_return_sequences: 1