General:
  operation: "synthesization"
  generator_name_or_path: "../models/Llama-3.2-3B-Instruct/FineTuned/Mainz-v3/checkpoint-105"
  discriminator_name_or_path: "../models/Llama-3.2-1B-Instruct/Base"

Data:
  prompt_template_path: "templates/generator_mainz_synthesization_v6.txt"
  discriminator_prompt_template_path: "templates/discriminiator_mainz.txt"
  sample_size: 1
  output_size: 1
  dataset_path: "data/private/kkr_data_cleaned_v2.csv"
  seed: 42

Generation:
  batch_size: 1
  output_dir: "../src/data/synthetic/mainz/v8_2"